city_to_cluster = {
    "Araçariguama": "Antares",
    "Atibaia": "Antares",
    "Bom Jesus dos Perdões": "Antares",
    "Araçariguama": "Antares",
    "Atibaia": "Antares",
    "Bom Jesus dos Perdões": "Antares",
    "Bragança Paulista": "Antares",
    "Cabreuva": "Antares",
    "Caieiras": "Antares",
    "Campinas": "Antares",
    "Campo Limpo Paulista": "Antares",
    "Francisco Morato": "Antares",
    "Franco da Rocha": "Antares",
    "Indaiatuba": "Antares",
    "Itupeva": "Antares",
    "Jarinu": "Antares",
    "Jundiai": "Antares",
    "Louveira": "Antares",
    "Holambra": "Antares",
    "Jaguariúna": "Antares",
    "Santo Antonio de Posse": "Antares",
    "Mariporã": "Antares",
    "Nazaré Paulista": "Antares",
    "Piracaia": "Antares",
    "Valinhos": "Antares",
    "Varzea Paulista": "Antares",
    "Vinhedo": "Antares",
    "Hortolândia": "Antares",
    "Caçapava": "Vega",
    "Jacareí": "Vega",
    "São Jose do Rio Preto": "Vega",
    "São José dos Campos ": "Vega",
    "Taubaté": "Vega",
    "bady bassitt": "Vega",
    "Mirassol": "Vega",
    "Cubatão": "Polaris",
    "Diadema": "Polaris",
    "Guarujá": "Polaris",
    "Itanhaém": "Polaris",
    "Mongaguá": "Polaris",
    "Peruíbe": "Polaris",
    "Praia Grande": "Polaris",
    "Santos": "Polaris",
    "São Bernado do Campo": "Polaris",
    "São Vicente": "Polaris",
    "Americana": "Sirius",
    "Araras": "Sirius",
    "Capivari": "Sirius",
    "Casa Branca": "Sirius",
    "Conchal": "Sirius",
    "Cordeiropolis": "Sirius",
    "Cosmopolis": "Sirius",
    "Cravinhos": "Sirius",
    "Engenheiro Coelho": "Sirius",
    "Estiva Gerbi": "Sirius",
    "Iracemapolis": "Sirius",
    "Leme": "Sirius",
    "Limeira": "Sirius",
    "Mogi Guaçu": "Sirius",
    "Mogi Mirim": "Sirius",
    "Monte Mor": "Sirius",
    "Nova Odessa": "Sirius",
    "Paulinia": "Sirius",
    "Piracicaba": "Sirius",
    "Pirassununga": "Sirius",
    "Porto Ferreira": "Sirius",
    "Rafard": "Sirius",
    "Rio Claro": "Sirius",
    "Santa Barbara D'Oeste": "Sirius",
    "Santa Cruz das Palmeiras": "Sirius",
    "Santa Gertrudes": "Sirius",
    "Santa Rta do Passa Quatro": "Sirius",
    "Sorocaba": "Sirius",
    "Votorantim": "Sirius",
    "Sumaré": "Sirius",
    "Aguai": "Sirius",
    "Bebedouro": "NetBarretos",
    "Colina": "NetBarretos",
    "Jaborandi": "NetBarretos",
    "Olimpia": "NetBarretos",
    "Pitangueiras": "NetBarretos",
}
